In [1]:
import numpy as np
import pandas as pd

In [6]:
text = np.array([
    'I love Vietnam. Vietnam!',
    'Vietnam is best',
    'Hochiminh is the biggest city of Vietnam'
])
text

array(['I love Vietnam. Vietnam!', 'Vietnam is best',
       'Hochiminh is the biggest city of Vietnam'], dtype='<U40')

In [7]:
y = np.array([0, 0, 1]) #target

In [8]:
#create bag of words
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
#khởi tạo CountVectorizer model
count = CountVectorizer()

In [10]:
# huấn luyện CountVectorizer model
count.fit(text)

CountVectorizer()

In [11]:
# biến đổi text -> bag of words
bag_of_words = count.transform(text)
bag_of_words

<3x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [12]:
X = bag_of_words.toarray()
X

array([[0, 0, 0, 0, 0, 1, 0, 0, 2],
       [1, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 1, 1]], dtype=int64)

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
model = MultinomialNB()

In [16]:
model.fit(X, y)

MultinomialNB()

In [17]:
# kiểm tra độ chính xác trên train
print('model accuracy:', model.score(X, y) * 100, '%')

model accuracy: 100.0 %


In [18]:
# kiểm tra trên dữ liệu mới
text_test = np.array(['Vietnam is beautiful country',
                      'I live in Hochiminh city'])

In [20]:
# tạo bag of words
X_test = count.transform(text_test).toarray()
X_test

array([[0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 0, 0, 0]], dtype=int64)

In [21]:
y_predict = model.predict(X_test)
y_predict

array([0, 1])

## Lưu lại model
### sử dụng thư viện pickle

In [22]:
import pickle

In [23]:
# lưu model MultinomialNB
filename1 = 'naive_model.pkl'
with open(filename1, 'wb') as f:
    pickle.dump(model, f)

In [24]:
# lưu CountVectorizer model
filename2 = 'count_model.pkl'
with open(filename2, 'wb') as f:
    pickle.dump(count, f)

## Load model để sử dụng

In [25]:
# đọc model MultinomialNB
filename1 = 'naive_model.pkl'
with open(filename1, 'rb') as f:
    naive_model = pickle.load(f)

In [26]:
# đọc Countvectorizer model
filename2 = 'count_model.pkl'
with open(filename2, 'rb') as f:
    count_model = pickle.load(f)

In [33]:
text_new = np.array(['Hochiminh city in my heart',
                     "Hanoi is capital of Vietnam"])

In [34]:
# tạo bag of words
X_new = count_model.transform(text_new).toarray()
X_new

array([[0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 1]], dtype=int64)

In [35]:
y_new = naive_model.predict(X_new)
y_new

array([1, 0])